apiVersion: apps/v1
kind: Deployment
metadata:
  name: cappy-queue-worker
  labels:
    app.kubernetes.io/name: cappy-queue-worker
spec:
  replicas: {{ .Values.queueWorker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cappy-queue-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cappy-queue-worker
    spec:
      containers:
        - name: queue-worker
          image: "{{ .Values.image.tag }}"
          command: ["php", "/var/www/artisan", "queue:work", "--sleep=3", "--tries=3", "--timeout=3600"]
          envFrom:
            - secretRef:
                name: cappy-secrets
          env:
            - name: APP_ENV
              value: {{ .Values.application.env | quote }}
            - name: APP_DEBUG
              value: {{ .Values.application.debug | quote }}
            - name: APP_URL
              value: {{ .Values.application.url | quote }}
            - name: ASSET_URL
              value: {{ .Values.application.url | quote }}
            - name: LOG_CHANNEL
              value: stderr
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: MAIL_PORT
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
          resources:
            limits:
              cpu: {{ .Values.queueWorker.resources.limits.cpu }}
              memory: {{ .Values.queueWorker.resources.limits.memory }}
            requests:
              cpu: {{ .Values.queueWorker.resources.requests.cpu }}
              memory: {{ .Values.queueWorker.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: cappy-app-shared-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: 600