replicaCount: 1

revisionHistoryLimit: 3

image:
  repository: ghcr.io/bcgov/cappy
  pullPolicy: Always
  tag: ""

resources:
  requests:
    cpu: "390m"
    memory: "1Gi"
  limits:
    cpu: "390m"
    memory: "1Gi"

pvc:
  storage: "64Mi"
  formData:
    storage: "64Mi"

db:
  host: "postgres"
  port: 5432
  name: "laravel"
  username: "laravel"
  password: "<app-db-password>"

queueWorker:
  replicaCount: 1
  resources:
    limits:
      cpu: "30m"
      memory: "128Mi"
    requests:
      cpu: "30m"
      memory: "128Mi"